AWSTemplateFormatVersion: "2010-09-09"
Description: ECS Repository

Parameters:
  RepositoryName:
    Type: String

Resources:
  ECSRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName